import { getSession, signIn, signUp, signOut, getHubAccessRole, fetchHubContent, fetchProfiles, fetchMemberships, fetchStaffRoles, fetchProgress, fetchPosts, fetchComments, createPost, createCloudComment, removeCloudPost, removeCloudComment, upsertHubContent, removeHubContent, upsertProgress, updateProfile, updateMembership, setMemberAccess, permanentlyDeleteMember, assignModerator } from "./cloud.js";

let accessRole = location.protocol === "file:" ? "Owner" : "Guest";
try { if(location.protocol !== "file:") accessRole = await getHubAccessRole(); } catch {}
const spaces = ["All activity", "Introduce Yourself", "Wins & Celebrations", "Creating More Income Options", "Social Media & Content", "AI & Productivity", "Personal Growth", "Accountability Corner", "Ask April"];
const categories = [
  ["Responsibility", "Own your choices and create momentum.", "6 lessons", "✓"],
  ["Resourcefulness", "Turn what you already have into options.", "8 lessons", "↗"],
  ["Communication", "Connect clearly and confidently.", "5 lessons", "“”"],
  ["Social Media", "Show up online with purpose.", "12 lessons", "#"],
  ["AI Tools", "Use AI to save time and create more.", "9 lessons", "✦"],
  ["Business Skills", "Build foundations that support growth.", "10 lessons", "▥"],
  ["Leadership", "Lead yourself and others well.", "7 lessons", "♧"],
  ["Creating Options Framework", "April's signature step-by-step framework.", "11 lessons", "◇"]
];
const defaultPosts = [
  {name:"Nina Foster", initials:"NF", avatar:"avatar-nina", space:"Wins & Celebrations", time:"28 min ago", text:"A small win that feels very big: I sent my first proposal today. I almost talked myself out of it, then remembered that confidence comes after the action.", likes:18, comments:[["Samantha Lee","This is huge, Nina. Cheering you on!"]]},
  {name:"April", initials:"A", avatar:"avatar-april", space:"Ask April", time:"2 hrs ago", text:"Monday reminder: you do not need the whole plan. You need one honest next move. What is yours this week?", likes:31, comments:[["Jay Williams","Mine is finally publishing the landing page."]]},
  {name:"Samantha Lee", initials:"SL", avatar:"avatar-sam", space:"AI & Productivity", time:"Yesterday", text:"I used the weekly planning prompt from the Resource Vault and saved at least an hour. Sharing the win because simple systems really do add up.", likes:24, comments:[]}
];
let userPosts = JSON.parse(localStorage.getItem("oyo-community-posts") || "[]");
let currentSpace = "All activity";

const pageContent = document.querySelector("#pageContent");
const composer = document.querySelector("#composer");
function currentMemberIdentity(){
  const session=getSession(), profile=managedMembers?.find(member=>sameId(member.id,session?.user?.id));
  const emailName=session?.user?.email?.split("@")[0]?.replace(/[._-]+/g," ");
  const name=profile?.name||session?.user?.user_metadata?.name||emailName||"Member";
  return {name,initials:initials(name),role:accessRole==="Owner"?"Owner":accessRole==="Moderator"?"Moderator":"Own Your Options member"};
}

function homePage() {
  const member=currentMemberIdentity();
  return `
    <div class="page-head"><div><span class="eyebrow">Welcome to Own Your Options</span><h1>Good morning, ${escapeHtml(member.name)}.</h1><p>Keep creating confidence, income, freedom, and fulfillment.</p></div><button class="text-button" data-page="start">View your pathway →</button></div>
    <div class="home-grid"><div>
      <section class="welcome card"><div class="welcome-copy"><span class="eyebrow">A message from April</span><h1>Own your <em>options.</em></h1><p>You have the power. You have the choices. You can create more options.</p></div><div class="play-wrap"><button class="play">▶</button><small>Watch April's welcome · 2:14</small></div></section>
      <section class="section"><div class="section-head"><h2>This week's challenge</h2><button class="text-button" data-page="challenges">View challenge →</button></div>
        <div class="challenge card"><div class="challenge-icon">↗</div><div><h3>Make One New Option</h3><p>Take one small action that creates a future possibility.</p><div class="progress"><i style="width:60%"></i></div></div><div class="challenge-meta"><strong>3 / 5</strong>steps complete</div></div>
      </section>
      <section class="section"><div class="section-head"><h2>Featured training</h2><button class="text-button" data-page="learn">Browse all training →</button></div>
        <div class="training-grid">${categories.slice(1,4).map((c,i)=>`<article class="training-card card"><div class="training-art ${["green","orange","gold"][i]}">${c[3]}</div><div class="body"><h3>${c[0]}: ${["Creating Choices Before You Need Them","Tell Your Story With Confidence","Build a Simple Content Rhythm"][i]}</h3><small>▶ ${[12,18,9][i]} min · ${c[2]}</small></div></article>`).join("")}</div>
      </section>
    </div><aside class="side-column">
      <section class="event-card card"><div class="event-top"><span class="eyebrow">Up next · Tuesday</span><h2>Ask April: Live Q&A</h2><p>Bring your questions, ideas, and stuck points.</p></div><div class="event-details"><div class="detail-row"><span>□</span> June 16 · 12:00 PM MT</div><div class="detail-row"><span>♙</span> 24 members attending</div><button class="primary" data-page="events">Save my spot</button></div></section>
      <section class="wins card"><div class="section-head"><h3>Member wins</h3><button class="text-button" data-page="community">See all</button></div><div class="win"><div class="avatar avatar-nina">NF</div><div><strong>Nina launched her first offer</strong><p>"I stopped waiting for perfect."</p><small>28 min ago · ♡ 18</small></div></div><div class="win"><div class="avatar avatar-jay">JW</div><div><strong>Jay booked a new client</strong><p>"The communication training worked."</p><small>Yesterday · ♡ 31</small></div></div></section>
      <section class="joined card"><div><strong>12 new members</strong><small>joined this week</small></div><div class="member-stack"><div class="avatar avatar-sam">SL</div><div class="avatar avatar-jay">JW</div><div class="avatar avatar-nina">NF</div></div></section>
    </aside></div>`;
}

function postCard(post, idx) {
  const comments = post.comments || [];
  return `<article class="post card" data-index="${idx}" data-post-id="${post.id||""}"><div class="post-head"><div class="avatar ${post.avatar}">${post.initials}</div><div><strong>${post.name}</strong><small>${post.time}</small></div><span class="space-tag">${post.space}</span></div><p>${escapeHtml(post.text)}</p>${post.image ? `<img class="post-image" src="${post.image}" alt="Shared by ${post.name}">`:""}<div class="post-actions"><button class="like-button">♡ <span>${post.likes || 0}</span> Like</button><button class="comment-toggle">▢ ${comments.length} Comment</button><button>↗ Share</button></div><div class="comments">${comments.map(c=>`<div class="comment"><div class="avatar avatar-sam">${c[0].split(" ").map(x=>x[0]).join("")}</div><div><strong>${c[0]}</strong><p>${escapeHtml(c[1])}</p></div></div>`).join("")}</div><form class="comment-form"><input required placeholder="Write a supportive comment..."><button>Send</button></form></article>`;
}

function communityPage() {
  const member=currentMemberIdentity();
  const all = [...userPosts, ...defaultPosts].filter(p => currentSpace === "All activity" || p.space === currentSpace);
  return `<div class="page-head"><div><span class="eyebrow">The Own Your Options Collective</span><h1>Community</h1><p>Connect with people creating options, taking responsibility, and building freedom.</p></div></div>
  <div class="page-layout"><aside class="spaces card"><h3>Spaces</h3>${spaces.map(s=>`<button class="space-button ${s===currentSpace?"active":""}" data-space="${s}">${s}</button>`).join("")}</aside>
  <section class="feed"><div class="quick-post card"><div class="avatar avatar-ap">${member.initials}</div><button id="quickPost">Share a win, question, or idea...</button></div>${all.length ? all.map(postCard).join("") : `<div class="empty card">No posts here yet. Start the conversation.</div>`}</section>
  <aside class="community-aside card"><div class="prompt-box card"><span>WEEKLY PROMPT</span><p>What is one thing you know now that you wish you knew a year ago?</p></div><h3 style="margin-top:18px">Online now</h3><div class="online-list">${[["April","A","avatar-april"],["Samantha Lee","SL","avatar-sam"],["Jay Williams","JW","avatar-jay"],["Nina Foster","NF","avatar-nina"]].map(x=>`<div class="online"><div class="avatar ${x[2]}">${x[1]}</div>${x[0]}<i></i></div>`).join("")}</div></aside></div>`;
}

function learnPage() {
  return `<div class="page-head"><div><span class="eyebrow">The Own Your Options Framework</span><h1>Learn</h1><p>Practical skills for creating confidence, income, freedom, and fulfillment.</p></div><button class="primary">Continue learning</button></div><div class="framework-strip">${["Own your reality","Define your future","Create more options","Implement with intention","Build freedom"].map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join("")}</div><div class="category-grid">${categories.map(c=>`<article class="category-card card"><div class="symbol">${c[3]}</div><h3>${c[0]}</h3><p>${c[1]}</p><small>${c[2]} →</small></article>`).join("")}</div>`;
}

function startPage() {
  return `<div class="page-head"><div><span class="eyebrow">A path made for you</span><h1>Start Here</h1><p>Answer one question and we'll point you toward the best place to begin.</p></div></div><section class="pathway card" id="quiz"><span class="eyebrow">Pathway quiz · 1 of 1</span><h1 style="margin-top:10px">What would make the biggest difference right now?</h1><p style="font-size:10px">There is no wrong answer. Pick the one that feels most useful today.</p><div class="quiz-options">${[["income","I need more income options"],["skills","I want stronger business skills"],["confidence","I'm looking for confidence"],["starting","I'm starting over"],["retirement","I'm getting near retirement"]].map(x=>`<button class="quiz-option" data-result="${x[0]}">${x[1]}</button>`).join("")}</div></section>`;
}

function eventsPage() {
  const events = [["16","JUN","Ask April: Live Q&A","Tuesday · 12:00 PM MT · Weekly live training"],["24","JUN","Build Your Options Map","Wednesday · 6:00 PM MT · Monthly workshop"],["02","JUL","Guest Expert: Simple Sales","Thursday · 12:00 PM MT · Guest session"],["07","JUL","Community Co-working Hour","Tuesday · 10:00 AM MT · Accountability session"]];
  return `<div class="page-head"><div><span class="eyebrow">Learn live, together</span><h1>Live Events</h1><p>Trainings, workshops, guest experts, and real-time support.</p></div><button class="primary">Add all to calendar</button></div><div class="event-list">${events.map(e=>`<article class="event-row card"><div class="date-box"><strong>${e[0]}</strong><small>${e[1]}</small></div><div><h3>${e[2]}</h3><p>${e[3]}</p></div><button class="primary rsvp">Save my spot</button></article>`).join("")}</div>`;
}

function coachingPage() {
  return `<div class="page-head"><div><span class="eyebrow">Guidance + accountability</span><h1>Coaching Hub</h1><p>Deeper support for turning insight into meaningful action.</p></div></div><section class="locked-hero card"><div><span class="eyebrow">Own Your Options Coaching</span><h1 style="margin-top:9px">You don't do this alone.</h1><p>Join April and a focused group of members for coaching, accountability, practical plans, and honest momentum.</p><button class="primary">Explore coaching membership</button></div><div class="coaching-portrait"></div></section><div class="benefits">${["Weekly group coaching calls","Replays + action plans","Accountability check-ins","Worksheets that create clarity","Monthly office hours","A focused coaching community"].map((x,i)=>`<article class="benefit card"><span class="eyebrow">0${i+1}</span><h3 style="margin-top:8px">${x}</h3><p>Practical support designed to help you keep moving.</p></article>`).join("")}</div>`;
}

function challengesPage() {
  const items=[["7","7 Day Resourcefulness Challenge","Find new possibilities in what you already have."],["30","30 Day Options Challenge","Create meaningful choices for your future."],["#","Content Challenge","Build a simple, sustainable sharing rhythm."],["↑","Confidence Challenge","Build confidence through small brave actions."]];
  return `<div class="page-head"><div><span class="eyebrow">Small actions, real momentum</span><h1>Challenges</h1><p>Choose a guided challenge and do it alongside the community.</p></div></div><div class="challenge-grid">${items.map((x,i)=>`<article class="challenge-card card"><div class="challenge-banner">${x[0]}</div><div class="body"><span class="eyebrow">${i===0?"Popular now":"Start anytime"}</span><h3 style="margin-top:7px">${x[1]}</h3><p>${x[2]}</p><button class="primary">Join challenge</button></div></article>`).join("")}</div>`;
}

function resourcesPage() {
  const items=[["PDF","My Options Map","A one-page worksheet for seeing your possibilities."],["AI","Weekly Planning Prompt","Turn your priorities into a practical weekly plan."],["DOC","Simple Offer Builder","Shape your skills into a clear, useful offer."],["PDF","Confidence Checklist","A grounded reset before a brave action."],["LINK","Content Idea Bank","50 useful prompts for showing up online."],["PDF","Conversation Planner","Prepare for clear, confident conversations."]];
  return `<div class="page-head"><div><span class="eyebrow">Tools you can use today</span><h1>Resource Vault</h1><p>Templates, prompts, PDFs, checklists, and trusted links.</p></div></div><div class="resource-filter">${["All resources","Templates","AI prompts","Checklists","Links"].map((x,i)=>`<button class="pill ${i===0?"active":""}">${x}</button>`).join("")}</div><div class="resource-grid">${items.map(x=>`<article class="resource-card card"><div class="file-type">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><small>Open resource →</small></article>`).join("")}</div>`;
}

function membersPage() {
  const people=managedMembers.filter(member=>member.visible && member.accessStatus==="Active");
  return `<div class="page-head"><div><span class="eyebrow">Find your people</span><h1>Member Directory</h1><p>Connect through location, skills, business interests, and goals.</p></div><button class="primary">Edit my profile</button></div><div class="resource-filter">${["All members","Near me","Shared goals","Shared interests"].map((x,i)=>`<button class="pill ${i===0?"active":""}">${x}</button>`).join("")}</div><div class="members-grid">${people.map(member=>`<article class="member-card card"><div class="avatar ${member.avatar}">${initials(member.name)}</div><h3>${escapeHtml(member.name)}</h3><p>⌖ ${escapeHtml(member.location)}</p><p>${escapeHtml(member.bio||"Creating more options.")}</p><div class="tags">${member.interests.split(",").map(t=>`<span class="tag">${escapeHtml(t.trim())}</span>`).join("")}</div></article>`).join("")}</div>`;
}

const starterMembers=[
  {id:1,name:"April Lungal",email:"april@ownyouroptions.com",location:"Alberta",interests:"Leadership, Business",goals:"Grow the Collective",bio:"Coach, mentor, and founder of Own Your Options.",status:"Active",visible:true,plan:"Owner",role:"Owner",progress:100,lastActive:"Today",avatar:"avatar-april"},
  {id:2,name:"Nina Foster",email:"nina@example.com",location:"Ontario",interests:"New business, Confidence",goals:"Launch first offer",bio:"Creating a new income option.",status:"Active",visible:true,plan:"Collective",progress:68,lastActive:"Today",avatar:"avatar-nina"},
  {id:3,name:"Jay Williams",email:"jay@example.com",location:"Colorado",interests:"Sales, Communication",goals:"Find three clients",bio:"Building a service business.",status:"Active",visible:true,plan:"Coaching",progress:82,lastActive:"Yesterday",avatar:"avatar-jay"},
  {id:4,name:"Samantha Lee",email:"sam@example.com",location:"British Columbia",interests:"AI, Productivity",goals:"Create more time",bio:"Using better systems to build freedom.",status:"Active",visible:true,plan:"Collective",progress:54,lastActive:"Today",avatar:"avatar-sam"},
  {id:5,name:"Morgan Reed",email:"morgan@example.com",location:"Texas",interests:"Content, Coaching",goals:"Grow an audience",bio:"Sharing useful ideas consistently.",status:"Active",visible:true,plan:"Collective",progress:36,lastActive:"3 days ago",avatar:"avatar-ap"},
  {id:6,name:"Taylor Khan",email:"taylor@example.com",location:"Nova Scotia",interests:"Starting over, Leadership",goals:"Choose a new direction",bio:"Designing the next chapter.",status:"Paused",visible:false,plan:"Collective",progress:22,lastActive:"2 weeks ago",avatar:"avatar-nina"}
];
const starterContent=[
  {id:101,title:"Responsibility Creates Options",area:"Learn",type:"Lesson",status:"Published",description:"See where your power lives and choose one useful action."},
  {id:102,title:"My Options Map",area:"Resource Vault",type:"PDF",status:"Published",description:"A one-page worksheet for seeing your possibilities."},
  {id:103,title:"Ask April: Live Q&A",area:"Live Events",type:"Live session",status:"Published",description:"Bring your questions, ideas, and stuck points."},
  {id:104,title:"7 Day Resourcefulness Challenge",area:"Challenges",type:"Challenge",status:"Published",description:"Use what you already have to create momentum."},
  {id:105,title:"Overcoming Overwhelm",area:"Coaching Hub",type:"Replay",status:"Draft",description:"Turn an overloaded mind into one clear decision."}
];
let managedMembers=JSON.parse(localStorage.getItem("oyo-hub-members")||"null")||starterMembers;
let managedContent=JSON.parse(localStorage.getItem("oyo-hub-content")||"null")||starterContent;
managedMembers.forEach(member=>member.completions??={});
managedMembers.forEach(member=>member.role??="Member");
managedMembers.forEach(member=>{member.accessStatus??=member.status==="Paused"?"Suspended":"Active";member.internalNotes??="";member.statusReason??="";member.archivedAt??="";});
managedMembers.forEach(member=>{if(member.email==="april@ownyouroptions.com"||member.role==="Admin"){member.role="Owner";member.plan="Owner";}});
let adminTab="overview";
const saveMembers=()=>localStorage.setItem("oyo-hub-members",JSON.stringify(managedMembers));
const saveContent=()=>localStorage.setItem("oyo-hub-content",JSON.stringify(managedContent));
const initials=name=>name.split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase();
const sameId=(a,b)=>String(a)===String(b);
let cloudReady=false;

async function syncCloudData(){
  if(!getSession()) return;
  try {
    const [content,profiles,memberships,roles,progress,posts,comments]=await Promise.all([fetchHubContent(),fetchProfiles(),fetchMemberships(),fetchStaffRoles(),fetchProgress(),fetchPosts(),fetchComments()]);
    if(content?.length) managedContent=content.map(x=>({id:x.id,title:x.title,area:x.area,type:x.type,status:x.status,description:x.description||""}));
    if(profiles?.length){
      const membershipsById=new Map((memberships||[]).map(x=>[x.user_id,x])), rolesById=new Map((roles||[]).map(x=>[x.user_id,x])), progressById=new Map();
      (progress||[]).forEach(x=>{const list=progressById.get(x.user_id)||[];list.push(x);progressById.set(x.user_id,list)});
      managedMembers=profiles.map((profile,index)=>{const membership=membershipsById.get(profile.user_id)||{},records=progressById.get(profile.user_id)||[],completions={};records.forEach(x=>completions[x.content_id]=x.percent===100);return{id:profile.user_id,name:profile.display_name,email:membership.email||"",location:profile.province_state||"",interests:[...(profile.skills||[]),...(profile.business_interests||[])].join(", ")||"Creating options",goals:(profile.goals||[]).join(", ")||"Create more options",bio:profile.bio||"",status:membership.status||"Active",accessStatus:membership.status||"Active",visible:profile.directory_visible,plan:membership.plan||"Collective",role:accessRole==="Owner"&&profile.user_id===getSession().user.id?"Owner":rolesById.has(profile.user_id)?"Moderator":"Member",progress:records.length?Math.round(records.reduce((a,x)=>a+x.percent,0)/records.length):0,lastActive:membership.last_active_at?new Date(membership.last_active_at).toLocaleDateString():"Not yet",avatar:["avatar-ap","avatar-nina","avatar-jay","avatar-sam"][index%4],completions,internalNotes:membership.admin_notes||"",statusReason:membership.status_reason||"",archivedAt:membership.archived_at||""}});
    }
    if(posts){
      userPosts=posts.map(post=>({id:post.id,userId:post.user_id,name:managedMembers.find(x=>sameId(x.id,post.user_id))?.name||"Member",initials:initials(managedMembers.find(x=>sameId(x.id,post.user_id))?.name||"Member"),avatar:"avatar-ap",space:post.space,time:new Date(post.created_at).toLocaleDateString(),text:post.body,image:"",likes:0,comments:(comments||[]).filter(x=>sameId(x.post_id,post.id)).map(x=>[managedMembers.find(m=>sameId(m.id,x.user_id))?.name||"Member",x.body,x.id])}));
    }
    saveMembers();saveContent();localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));cloudReady=true;
  } catch(error) { console.warn("Cloud sync unavailable:",error.message); }
}
await syncCloudData();

function adminPage(){
  if(accessRole!=="Owner") return `<section class="pathway card"><span class="eyebrow">Private owner area</span><h1>April Admin is owner-only.</h1><p>This signed-in account does not have permission to access the private back office.</p><button class="primary" data-page="home">Return home</button></section>`;
  return `<div class="owner-lock"><span>◆</span> Owner-only back office · Only April's authenticated account can open this area</div><div class="page-head"><div><span class="eyebrow">Private owner back office</span><h1>April Admin</h1><p>Manage the Collective, its members, and their progress.</p></div><button class="primary" id="exportMembers">Export members</button></div>
  <div class="admin-tabs">${[["overview","Overview"],["content","Content"],["members","Members"],["progress","Progress"],["moderation","Community"],["roles","Team & Roles"],["housekeeping","Housekeeping"]].map(x=>`<button class="${adminTab===x[0]?"active":""}" data-admin-tab="${x[0]}">${x[1]}</button>`).join("")}</div><div id="adminPanel">${adminPanelMarkup()}</div>`;
}
function adminPanelMarkup(){
  if(adminTab==="overview"){
    const active=managedMembers.filter(x=>x.accessStatus==="Active").length, avg=Math.round(managedMembers.reduce((a,x)=>a+x.progress,0)/managedMembers.length);
    return `<div class="admin-metrics">${[["Members",managedMembers.length,"Total member records"],["Active",active,"Able to access the hub"],["Average progress",avg+"%","Across all members"],["Published",managedContent.filter(x=>x.status==="Published").length,"Visible content items"]].map(x=>`<article class="metric-card card"><span class="eyebrow">${x[0]}</span><strong>${x[1]}</strong><p>${x[2]}</p></article>`).join("")}</div>
    <div class="admin-two"><section class="admin-box card"><h2>What you can manage</h2><div class="admin-checklist">${["Add, edit, publish, draft, or remove content","Control which members appear in the directory","Review each member's completion and last activity","Activate, pause, or remove member accounts","Assign moderators with limited permissions","Moderate posts shared in the community"].map(x=>`<p>✓ ${x}</p>`).join("")}</div></section><section class="admin-box card"><span class="eyebrow">Needs attention</span><h2>Member follow-up</h2>${managedMembers.filter(x=>x.progress<50).map(x=>`<div class="attention-row"><div class="avatar ${x.avatar}">${initials(x.name)}</div><div><strong>${x.name}</strong><small>${x.progress}% complete · ${x.lastActive}</small></div></div>`).join("")}</section></div>`;
  }
  if(adminTab==="content") return `<div class="admin-two"><section class="admin-box card"><span class="eyebrow">Content editor</span><h2>Add something new</h2><form class="admin-form" id="adminContentForm"><label>Title<input id="adminContentTitle" required placeholder="Example: Creating income options"></label><div class="field-pair"><label>Appears in<select id="adminContentArea">${["Learn","Live Events","Coaching Hub","Challenges","Resource Vault"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Type<select id="adminContentType">${["Lesson","Video","PDF","Template","Live session","Replay","Challenge"].map(x=>`<option>${x}</option>`).join("")}</select></label></div><label>Description<textarea id="adminContentDescription" required placeholder="What members will learn or receive"></textarea></label><label>Status<select id="adminContentStatus"><option>Published</option><option>Draft</option></select></label><button class="primary">Save content</button></form></section><section class="admin-box card"><span class="eyebrow">Content library</span><h2>${managedContent.length} items</h2><div class="admin-list">${managedContent.map(x=>`<article class="admin-list-item"><div><small>${x.area} · ${x.type} · <b class="${x.status==="Published"?"success":"draft"}">${x.status}</b></small><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.description)}</p></div><div class="item-buttons"><button data-content-toggle="${x.id}">${x.status==="Published"?"Unpublish":"Publish"}</button><button class="danger" data-content-delete="${x.id}">Remove</button></div></article>`).join("")}</div></section></div>`;
  if(adminTab==="members") return `<div class="admin-two"><section class="admin-box card"><span class="eyebrow">Member onboarding</span><h2>How members join</h2><p class="account-note">New members choose <strong>Create a new member account</strong> from the sign-in screen. Their secure login, member record, and directory profile are created automatically.</p><div class="admin-checklist"><p>✓ Member confirms their email</p><p>✓ Database creates their profile</p><p>✓ You can then manage access and visibility</p><p>✓ Passwords remain private and secure</p></div><button class="primary wide" id="copyJoinLink">Copy member join link</button></section><section class="admin-box card"><span class="eyebrow">Active records</span><h2>${managedMembers.filter(x=>x.accessStatus!=="Archived").length} members</h2><div class="admin-list">${managedMembers.filter(x=>x.accessStatus!=="Archived").map(member=>memberAdminRow(member)).join("")}</div></section></div>`;
  if(adminTab==="progress") {
    const published=managedContent.filter(x=>x.status==="Published");
    return `<section class="admin-box card"><div class="section-head"><div><span class="eyebrow">Member progress</span><h2>See how people are moving</h2></div><span class="status-note">Tracked against the things you publish</span></div><div class="progress-table"><div class="progress-row progress-head"><span>Member</span><span>Plan</span><span>Progress</span><span>Last active</span><span>Complete</span></div>${managedMembers.map(member=>`<div class="progress-row"><span><strong>${member.name}</strong><small>${member.goals}</small></span><span>${member.plan}</span><span><div class="progress"><i style="width:${member.progress}%"></i></div><small>${member.progress}% complete</small></span><span>${member.lastActive}</span><span>${Object.values(member.completions).filter(Boolean).length} of ${published.length}</span></div>`).join("")}</div></section>
    <section class="admin-box card completion-section"><span class="eyebrow">Content-by-content tracking</span><h2>Completion details</h2><div class="completion-grid">${managedMembers.map(member=>`<article class="completion-member"><div class="member-admin-main"><div class="avatar ${member.avatar}">${initials(member.name)}</div><div><strong>${member.name}</strong><small>${member.progress}% overall</small></div></div><div>${published.map(item=>`<button class="${member.completions[item.id]?"done":""}" data-completion-member="${member.id}" data-completion-content="${item.id}"><span>${member.completions[item.id]?"✓":"○"}</span>${escapeHtml(item.title)}<small>${item.area}</small></button>`).join("")}</div></article>`).join("")}</div></section>`;
  }
  if(adminTab==="moderation") {
    const memberComments=userPosts.flatMap((post,postIndex)=>(post.comments||[]).map((comment,commentIndex)=>({postIndex,commentIndex,author:comment[0],body:comment[1],post:post.text})));
    return `<div class="moderator-banner card"><div><span class="eyebrow">Moderator workspace</span><h2>Community safety and support</h2><p>Moderators can review posts, remove inappropriate content, and help keep conversations organized. They cannot access private progress, change memberships, publish programs, or assign roles.</p></div><strong>${managedMembers.filter(x=>x.role==="Moderator"&&x.status==="Active").length}<small>active moderators</small></strong></div><div class="admin-two"><section class="admin-box card"><div class="section-head"><div><span class="eyebrow">Community moderation</span><h2>Member-created posts</h2></div><span class="status-note">${userPosts.length} posts</span></div><div class="admin-list">${userPosts.length?userPosts.map((post,i)=>`<article class="admin-list-item"><div><small>${post.space} · ${post.time}</small><strong>${post.name}</strong><p>${escapeHtml(post.text)}</p></div><button class="danger" data-post-delete="${i}">Remove post</button></article>`).join(""):`<div class="empty">No member-created posts need review.</div>`}</div></section><section class="admin-box card"><div class="section-head"><div><span class="eyebrow">Comment review</span><h2>Member comments</h2></div><span class="status-note">${memberComments.length} comments</span></div><div class="admin-list">${memberComments.length?memberComments.map(comment=>`<article class="admin-list-item"><div><small>On: ${escapeHtml(comment.post.slice(0,45))}</small><strong>${escapeHtml(comment.author)}</strong><p>${escapeHtml(comment.body)}</p></div><button class="danger" data-comment-post="${comment.postIndex}" data-comment-delete="${comment.commentIndex}">Remove</button></article>`).join(""):`<div class="empty">No member-created comments need review.</div>`}</div></section></div>`;
  }
  if(adminTab==="roles") return `<div class="roles-intro card"><div><span class="eyebrow">Team & permissions</span><h2>Add moderators when your community grows</h2><p>Choose trusted members to help manage conversations. They receive separate Moderator Tools and never receive access to April Admin.</p></div><div class="permission-legend"><span><b class="role-dot admin-dot"></b> Owner: April only</span><span><b class="role-dot mod-dot"></b> Moderator: Community only</span><span><b class="role-dot member-dot"></b> Member: No back-office access</span></div></div><section class="admin-box card"><div class="section-head"><div><span class="eyebrow">Role assignments</span><h2>Your team</h2></div><span class="status-note">Only April can change roles</span></div><div class="admin-list role-list">${managedMembers.filter(x=>x.accessStatus!=="Archived").map(member=>`<article class="admin-list-item"><div class="member-admin-main"><div class="avatar ${member.avatar}">${initials(member.name)}</div><div><small>${member.email}</small><strong>${member.name}</strong><p>${member.accessStatus} · ${member.plan}</p></div></div><div class="role-control"><span class="role-badge role-${member.role.toLowerCase()}">${member.role}</span>${member.role==="Owner"?`<small>Protected owner account</small>`:`<select data-member-role="${member.id}"><option ${member.role==="Member"?"selected":""}>Member</option><option ${member.role==="Moderator"?"selected":""}>Moderator</option></select>`}</div></article>`).join("")}</div></section><section class="permission-grid">${[["Owner","April Admin access","Only April can access content, members, progress, roles, settings, and moderation."],["Moderator","Separate Moderator Tools","Review and remove posts or comments. No access to April Admin."],["Member","Standard hub access","Join conversations, complete content, attend events, and appear in the directory."]].map((x,i)=>`<article class="card"><span class="role-badge role-${x[0].toLowerCase()}">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</section>`;
  return housekeepingMarkup();
}
function memberAdminRow(member){return `<article class="admin-list-item"><div class="member-admin-main"><div class="avatar ${member.avatar}">${initials(member.name)}</div><div><small>${member.email} · ${member.location}</small><strong>${member.name}</strong><p>${member.plan} · <b class="access-${member.accessStatus.toLowerCase()}">${member.accessStatus}</b> · Directory: ${member.visible?"Visible":"Hidden"}</p></div></div><div class="item-buttons"><button data-member-visible="${member.id}">${member.visible?"Hide":"Show"}</button>${member.role==="Owner"?"":`<button class="${member.accessStatus==="Blocked"?"restore":""}" data-member-block="${member.id}">${member.accessStatus==="Blocked"?"Unblock":"Block access"}</button><button data-member-archive="${member.id}">Archive</button>`}</div></article>`}
function housekeepingMarkup(){
  const blocked=managedMembers.filter(x=>x.accessStatus==="Blocked"), archived=managedMembers.filter(x=>x.accessStatus==="Archived");
  return `<div class="admin-metrics">${[["Blocked",blocked.length,"Cannot sign into the hub"],["Archived",archived.length,"Removed from active lists"],["Hidden",managedMembers.filter(x=>!x.visible).length,"Not shown in directory"],["Inactive",managedMembers.filter(x=>x.lastActive.includes("week")||x.lastActive==="Not yet").length,"May need follow-up"]].map(x=>`<article class="metric-card card"><span class="eyebrow">${x[0]}</span><strong>${x[1]}</strong><p>${x[2]}</p></article>`).join("")}</div><div class="housekeeping-note card"><span>!</span><p><strong>Block first, delete later.</strong> Blocking immediately prevents access while preserving history. Archive members you no longer need in active lists. Permanent deletion cannot be undone.</p></div><section class="admin-box card housekeeping-list"><span class="eyebrow">Member lifecycle</span><h2>Housekeeping controls</h2>${managedMembers.map(member=>`<article class="housekeeping-member"><div class="member-admin-main"><div class="avatar ${member.avatar}">${initials(member.name)}</div><div><strong>${member.name}</strong><small>${member.email} · ${member.accessStatus}${member.statusReason?` · ${escapeHtml(member.statusReason)}`:""}</small></div></div><label>Private owner notes<textarea data-notes="${member.id}" placeholder="Private notes only you can see">${escapeHtml(member.internalNotes)}</textarea></label><div class="item-buttons">${member.role==="Owner"?`<span class="role-badge role-owner">Protected owner</span>`:`${member.accessStatus==="Blocked"?`<button class="restore" data-member-block="${member.id}">Unblock access</button>`:`<button data-member-block="${member.id}">Block access</button>`}${member.accessStatus==="Archived"?`<button class="restore" data-member-restore="${member.id}">Restore</button><button class="danger" data-member-delete="${member.id}">Permanently delete</button>`:`<button data-member-archive="${member.id}">Archive</button>`}`}<button data-save-notes="${member.id}">Save notes</button></div></article>`).join("")}</section>`;
}
function moderatorPage(){
  if(accessRole!=="Moderator"&&accessRole!=="Owner") return `<section class="pathway card"><span class="eyebrow">Restricted area</span><h1>Moderator access required.</h1><p>This signed-in account does not have moderation permissions.</p><button class="primary" data-page="home">Return home</button></section>`;
  const comments=userPosts.flatMap((post,postIndex)=>(post.comments||[]).map((comment,commentIndex)=>({postIndex,commentIndex,author:comment[0],body:comment[1],post:post.text})));
  return `<div class="page-head"><div><span class="eyebrow">Community-only access</span><h1>Moderator Tools</h1><p>Review community conversations without access to April Admin.</p></div></div><div class="moderator-banner card"><div><span class="eyebrow">Limited permissions</span><h2>Keep the Collective welcoming and useful</h2><p>This workspace contains community moderation only. Member records, private progress, content publishing, roles, and business settings remain owner-only.</p></div></div><div class="admin-two"><section class="admin-box card"><h2>Member posts</h2><div class="admin-list">${userPosts.length?userPosts.map((post,i)=>`<article class="admin-list-item"><div><small>${post.space}</small><strong>${post.name}</strong><p>${escapeHtml(post.text)}</p></div><button class="danger" data-post-delete="${i}">Remove</button></article>`).join(""):`<div class="empty">No member posts need review.</div>`}</div></section><section class="admin-box card"><h2>Member comments</h2><div class="admin-list">${comments.length?comments.map(comment=>`<article class="admin-list-item"><div><small>On: ${escapeHtml(comment.post.slice(0,45))}</small><strong>${escapeHtml(comment.author)}</strong><p>${escapeHtml(comment.body)}</p></div><button class="danger" data-comment-post="${comment.postIndex}" data-comment-delete="${comment.commentIndex}">Remove</button></article>`).join(""):`<div class="empty">No comments need review.</div>`}</div></section></div>`;
}

const pages = {home:homePage, community:communityPage, learn:learnPage, start:startPage, events:eventsPage, coaching:coachingPage, challenges:challengesPage, resources:resourcesPage, members:membersPage, moderator:moderatorPage, admin:adminPage};
function render(page="home") {
  if(accessRole==="Guest"){
    pageContent.innerHTML=`<section class="pathway card access-denied"><span class="eyebrow">Own Your Options Collective</span><h1>Sign in to enter the member hub.</h1><p>Your community, training, resources, events, and progress live inside.</p><button class="primary" id="gatewaySignIn">Member sign in</button></section>`;
    document.querySelector("#gatewaySignIn").addEventListener("click",openAccount);
    return;
  }
  if(accessRole==="Blocked"){
    pageContent.innerHTML=`<section class="pathway card access-denied"><span class="eyebrow">Account unavailable</span><h1>Your access to the Own Your Options Collective is currently unavailable.</h1><p>Please contact April if you believe this is a mistake.</p></section>`;
    return;
  }
  pageContent.innerHTML = pages[page]();
  injectManagedContent(page);
  document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active", x.dataset.page===page));
  bindPageEvents(page);
  window.scrollTo({top:0, behavior:"smooth"});
}
function bindPageEvents(page) {
  pageContent.querySelectorAll("[data-page]").forEach(x=>x.addEventListener("click", e=>{e.preventDefault();render(x.dataset.page);document.querySelector(".sidebar").classList.remove("open")}));
  if(page==="community") {
    document.querySelector("#quickPost")?.addEventListener("click",()=>composer.showModal());
    document.querySelectorAll(".space-button").forEach(x=>x.addEventListener("click",()=>{currentSpace=x.dataset.space;render("community")}));
    document.querySelectorAll(".like-button").forEach(x=>x.addEventListener("click",()=>{x.classList.toggle("liked");const n=x.querySelector("span");n.textContent=+n.textContent+(x.classList.contains("liked")?1:-1)}));
    document.querySelectorAll(".comment-toggle").forEach(x=>x.addEventListener("click",()=>x.closest(".post").querySelector(".comment-form").classList.toggle("open")));
    document.querySelectorAll(".comment-form").forEach(f=>f.addEventListener("submit",async e=>{e.preventDefault();const body=f.querySelector("input").value,postId=f.closest(".post").dataset.postId,p=document.querySelector("#commentTemplate").content.cloneNode(true);if(cloudReady&&postId&&getSession())try{const result=await createCloudComment({post_id:postId,user_id:getSession().user.id,body});const post=userPosts.find(x=>sameId(x.id,postId));post?.comments.push([getSession().user.user_metadata?.name||"Member",body,result?.[0]?.id])}catch(error){return showToast(error.message)}p.querySelector("p").textContent=body;f.previousElementSibling.append(p);f.reset();f.classList.remove("open")}));
  }
  if(page==="start") document.querySelectorAll(".quiz-option").forEach(x=>x.addEventListener("click",()=>showResult(x.dataset.result)));
  if(page==="admin") bindAdminEvents();
  if(page==="moderator") bindModeratorEvents();
  document.querySelectorAll("[data-complete-content]").forEach(button=>button.addEventListener("click",async()=>{const contentId=button.dataset.completeContent,member=managedMembers.find(x=>sameId(x.id,getSession()?.user?.id));if(member){member.completions[contentId]=true;saveMembers()}if(cloudReady&&getSession())try{await upsertProgress({user_id:getSession().user.id,content_id:contentId,status:"Completed",percent:100,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});button.textContent="Completed ✓";button.classList.add("completed")}catch(e){showToast(e.message)}}));
  document.querySelectorAll(".rsvp").forEach(x=>x.addEventListener("click",()=>{x.textContent="You're going ✓";x.style.background="#df7546"}));
  document.querySelectorAll(".pill").forEach(x=>x.addEventListener("click",()=>{document.querySelectorAll(".pill").forEach(p=>p.classList.remove("active"));x.classList.add("active")}));
}
function injectManagedContent(page){
  const areas={learn:"Learn",events:"Live Events",coaching:"Coaching Hub",challenges:"Challenges",resources:"Resource Vault"};
  const area=areas[page]; if(!area)return;
  const items=managedContent.filter(x=>x.area===area&&x.status==="Published"); if(!items.length)return;
  const member=managedMembers.find(x=>sameId(x.id,getSession()?.user?.id));
  pageContent.insertAdjacentHTML("beforeend",`<section class="section managed-section"><div class="section-head"><div><span class="eyebrow">Added by April</span><h2>From your Own Your Options library</h2></div></div><div class="managed-grid">${items.map(x=>`<article class="resource-card card"><div class="file-type">${x.type.slice(0,4).toUpperCase()}</div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.description)}</p><button class="complete-button ${member?.completions?.[x.id]?"completed":""}" data-complete-content="${x.id}">${member?.completions?.[x.id]?"Completed ✓":"Mark complete"}</button></article>`).join("")}</div></section>`);
}
function bindAdminEvents(){
  document.querySelectorAll("[data-admin-tab]").forEach(button=>button.addEventListener("click",()=>{adminTab=button.dataset.adminTab;render("admin")}));
  document.querySelector("#exportMembers")?.addEventListener("click",exportMemberCsv);
  document.querySelector("#copyJoinLink")?.addEventListener("click",async()=>{await navigator.clipboard.writeText(location.origin+location.pathname);showToast("Member join link copied")});
  document.querySelector("#adminContentForm")?.addEventListener("submit",async event=>{event.preventDefault();const item={id:Date.now(),title:document.querySelector("#adminContentTitle").value.trim(),area:document.querySelector("#adminContentArea").value,type:document.querySelector("#adminContentType").value,status:document.querySelector("#adminContentStatus").value,description:document.querySelector("#adminContentDescription").value.trim()};managedContent.unshift(item);saveContent();if(cloudReady)try{await upsertHubContent(item)}catch(e){showToast(e.message)}render("admin")});
  document.querySelectorAll("[data-content-toggle]").forEach(button=>button.addEventListener("click",async()=>{const item=managedContent.find(x=>sameId(x.id,button.dataset.contentToggle));item.status=item.status==="Published"?"Draft":"Published";saveContent();if(cloudReady)try{await upsertHubContent(item)}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-content-delete]").forEach(button=>button.addEventListener("click",async()=>{const id=button.dataset.contentDelete;managedContent=managedContent.filter(x=>!sameId(x.id,id));saveContent();if(cloudReady)try{await removeHubContent(id)}catch(e){showToast(e.message)}render("admin")}));
  document.querySelector("#adminMemberForm")?.addEventListener("submit",event=>{event.preventDefault();managedMembers.unshift({id:Date.now(),name:document.querySelector("#memberName").value.trim(),email:document.querySelector("#memberEmail").value.trim(),location:document.querySelector("#memberLocation").value.trim(),interests:document.querySelector("#memberInterests").value.trim()||"Creating options",goals:document.querySelector("#memberGoals").value.trim()||"Create more options",bio:"New Own Your Options member.",status:"Active",accessStatus:"Active",visible:document.querySelector("#memberVisible").checked,plan:document.querySelector("#memberPlan").value,role:"Member",progress:0,lastActive:"Not yet",avatar:"avatar-ap",completions:{},internalNotes:"",statusReason:"",archivedAt:""});saveMembers();render("admin")});
  document.querySelectorAll("[data-member-visible]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.memberVisible));member.visible=!member.visible;saveMembers();if(cloudReady)try{await updateProfile(member.id,{directory_visible:member.visible})}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-member-block]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.memberBlock));const status=member.accessStatus==="Blocked"?"Active":"Blocked",reason=status==="Blocked"?(prompt("Private reason for blocking this member:")||"Blocked by owner"):"";member.accessStatus=status;member.statusReason=reason;if(status==="Blocked")member.visible=false;saveMembers();if(cloudReady)try{await setMemberAccess(member.id,status,reason)}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-member-archive]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.memberArchive));if(!confirm(`Archive ${member.name}? They will lose access and disappear from active lists.`))return;member.accessStatus="Archived";member.visible=false;member.archivedAt=new Date().toISOString();member.statusReason=member.statusReason||"Archived by owner";saveMembers();if(cloudReady)try{await setMemberAccess(member.id,"Archived",member.statusReason)}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-member-restore]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.memberRestore));member.accessStatus="Active";member.archivedAt="";member.statusReason="";saveMembers();if(cloudReady)try{await setMemberAccess(member.id,"Active","")}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-member-delete]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.memberDelete));if(member?.accessStatus!=="Archived"||!confirm(`Permanently delete ${member.name}? This cannot be undone.`))return;if(cloudReady)try{await permanentlyDeleteMember(member.id)}catch(e){return showToast(e.message)}managedMembers=managedMembers.filter(x=>!sameId(x.id,member.id));saveMembers();render("admin")}));
  document.querySelectorAll("[data-save-notes]").forEach(button=>button.addEventListener("click",async()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.saveNotes));member.internalNotes=document.querySelector(`[data-notes="${member.id}"]`).value.trim();saveMembers();if(cloudReady)try{await updateMembership(member.id,{admin_notes:member.internalNotes})}catch(e){showToast(e.message)}render("admin")}));
  document.querySelectorAll("[data-completion-member]").forEach(button=>button.addEventListener("click",()=>{const member=managedMembers.find(x=>sameId(x.id,button.dataset.completionMember));const contentId=button.dataset.completionContent;member.completions[contentId]=!member.completions[contentId];const published=managedContent.filter(x=>x.status==="Published");member.progress=published.length?Math.round(published.filter(x=>member.completions[x.id]).length/published.length*100):0;member.lastActive="Updated now";saveMembers();render("admin")}));
  document.querySelectorAll("[data-post-delete]").forEach(button=>button.addEventListener("click",async()=>{const post=userPosts[Number(button.dataset.postDelete)];if(cloudReady&&post.id)try{await removeCloudPost(post.id)}catch(e){return showToast(e.message)}userPosts.splice(Number(button.dataset.postDelete),1);localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));render("admin")}));
  document.querySelectorAll("[data-comment-delete]").forEach(button=>button.addEventListener("click",async()=>{const comment=userPosts[Number(button.dataset.commentPost)].comments[Number(button.dataset.commentDelete)];if(cloudReady&&comment[2])try{await removeCloudComment(comment[2])}catch(e){return showToast(e.message)}userPosts[Number(button.dataset.commentPost)].comments.splice(Number(button.dataset.commentDelete),1);localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));render("admin")}));
  document.querySelectorAll("[data-member-role]").forEach(select=>select.addEventListener("change",async()=>{const member=managedMembers.find(x=>sameId(x.id,select.dataset.memberRole));member.role=select.value;saveMembers();if(cloudReady)try{await assignModerator(member.id,member.role==="Moderator")}catch(e){showToast(e.message)}render("admin")}));
}
function bindModeratorEvents(){
  document.querySelectorAll("[data-post-delete]").forEach(button=>button.addEventListener("click",async()=>{const post=userPosts[Number(button.dataset.postDelete)];if(cloudReady&&post.id)try{await removeCloudPost(post.id)}catch(e){return showToast(e.message)}userPosts.splice(Number(button.dataset.postDelete),1);localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));render("moderator")}));
  document.querySelectorAll("[data-comment-delete]").forEach(button=>button.addEventListener("click",async()=>{const comment=userPosts[Number(button.dataset.commentPost)].comments[Number(button.dataset.commentDelete)];if(cloudReady&&comment[2])try{await removeCloudComment(comment[2])}catch(e){return showToast(e.message)}userPosts[Number(button.dataset.commentPost)].comments.splice(Number(button.dataset.commentDelete),1);localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));render("moderator")}));
}
function exportMemberCsv(){
  const quote=value=>`"${String(value??"").replaceAll('"','""')}"`;
  const rows=[["Name","Email","Location","Interests","Goal","Plan","Role","Status","Directory visible","Progress","Last active"],...managedMembers.map(x=>[x.name,x.email,x.location,x.interests,x.goals,x.plan,x.role,x.status,x.visible,x.progress,x.lastActive])];
  const blob=new Blob([rows.map(row=>row.map(quote).join(",")).join("\n")],{type:"text/csv"});
  const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="own-your-options-members.csv";link.click();URL.revokeObjectURL(link.href);
}
function showResult(type) {
  const results={income:["Creating More Income Options","Start with the Creating Options Framework, then join the income options conversation."],skills:["Business Skills","Build a practical foundation with short lessons and useful templates."],confidence:["Confidence Challenge","Small brave actions will help you build confidence from real evidence."],starting:["Start Again Pathway","Begin with clarity, resourcefulness, and a welcoming group who gets it."],retirement:["Your Next Chapter Pathway","Map your skills, interests, and possibilities for what comes next."]};
  document.querySelector("#quiz").innerHTML=`<span class="eyebrow">Your recommended pathway</span><div class="quiz-result"><h1>${results[type][0]}</h1><p>${results[type][1]}</p><button class="primary" data-page="${type==="confidence"?"challenges":"learn"}">Begin my pathway →</button></div><button class="text-button" style="margin-top:18px" data-page="start">Retake quiz</button>`;
  bindPageEvents("start");
}
function escapeHtml(text) { const d=document.createElement("div"); d.textContent=text; return d.innerHTML; }
function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
const accountDialog=document.querySelector("#accountDialog"),accountContent=document.querySelector("#accountContent");
function openAccount(){
  const session=getSession();
  document.querySelector("#accountTitle").textContent=session?"Your member account":"Member sign in";
  accountContent.innerHTML=session?`<p class="account-note">Signed in securely as <strong>${escapeHtml(session.user.email)}</strong>.</p><p class="account-success">${accessRole==="Owner"?"Owner access active":accessRole==="Moderator"?"Moderator access active":"Member access active"}</p><button class="primary wide" id="signOutButton">Sign out</button>`:`<form class="admin-form" id="signInForm"><label>Your name<input id="authName" autocomplete="name" placeholder="Needed only for a new account"></label><label>Email<input id="authEmail" type="email" autocomplete="email" required></label><label>Password<input id="authPassword" type="password" autocomplete="current-password" minlength="6" required></label><div id="authMessage"></div><button class="primary">Sign in</button><button class="text-button" id="createAccount" type="button">Create a new member account</button></form>`;
  accountDialog.showModal();
  document.querySelector("#signOutButton")?.addEventListener("click",()=>{signOut();location.reload()});
  document.querySelector("#signInForm")?.addEventListener("submit",async event=>{event.preventDefault();try{await signIn(document.querySelector("#authEmail").value,document.querySelector("#authPassword").value);location.reload()}catch(e){document.querySelector("#authMessage").textContent=e.message}});
  document.querySelector("#createAccount")?.addEventListener("click",async()=>{try{const name=document.querySelector("#authName").value.trim();if(!name)throw new Error("Enter your name first.");await signUp(document.querySelector("#authEmail").value,document.querySelector("#authPassword").value,name);document.querySelector("#authMessage").textContent="Account created. Check your email, confirm it, then sign in."}catch(e){document.querySelector("#authMessage").textContent=e.message}});
}
const signedInIdentity=currentMemberIdentity();
document.querySelector("#accountButton").textContent=getSession()?signedInIdentity.initials:"Sign in";
document.querySelector("#sidebarAvatar").textContent=getSession()?signedInIdentity.initials:"YO";
document.querySelector("#sidebarMemberName").textContent=getSession()?signedInIdentity.name:"Your account";
document.querySelector("#sidebarMemberRole").textContent=getSession()?signedInIdentity.role:"Own Your Options member";
document.querySelector("#commentTemplate .avatar").textContent=signedInIdentity.initials;
document.querySelector("#commentTemplate strong").textContent=signedInIdentity.name;
document.querySelector("#accountButton").addEventListener("click",openAccount);
document.querySelector("#closeAccount").addEventListener("click",()=>accountDialog.close());
document.querySelector("#openComposer").addEventListener("click",()=>{if(!getSession()&&location.protocol!=="file:")return openAccount();composer.showModal()});
document.querySelector(".admin-nav").hidden=accessRole!=="Owner";
document.querySelector(".moderator-nav").hidden=accessRole!=="Moderator";
document.querySelector(".mobile-menu").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));
document.querySelectorAll(".sidebar [data-page]").forEach(x=>x.addEventListener("click",e=>{e.preventDefault();render(x.dataset.page);document.querySelector(".sidebar").classList.remove("open")}));
document.querySelector("#postImage").addEventListener("change", e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader();r.onload=()=>document.querySelector("#imagePreview").innerHTML=`<img src="${r.result}" alt="Preview">`;r.readAsDataURL(f)});
document.querySelector("#postForm").addEventListener("submit",async e=>{e.preventDefault();const img=document.querySelector("#imagePreview img"),member=currentMemberIdentity(),post={name:member.name,initials:member.initials,avatar:"avatar-ap",space:document.querySelector("#postSpace").value,time:"Just now",text:document.querySelector("#postText").value,image:img?.src||"",likes:0,comments:[]};if(cloudReady&&getSession())try{const result=await createPost({user_id:getSession().user.id,space:post.space,body:post.text});post.id=result?.[0]?.id}catch(error){return showToast(error.message)}userPosts.unshift(post);localStorage.setItem("oyo-community-posts",JSON.stringify(userPosts));e.target.reset();document.querySelector("#imagePreview").innerHTML="";composer.close();currentSpace="All activity";render("community")});
render();
